# Generated by Django 6.0.5 on 2026-05-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.FloatField(default=0)),
                ('temperature', models.FloatField(default=0)),
                ('pump_status', models.BooleanField(default=False)),
                ('esp32_connected', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('auto', 'Automatique'), ('manual', 'Manuel')], default='auto', max_length=10)),
                ('threshold', models.FloatField(default=30)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
