# Generated by Django 6.0.5 on 2026-06-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemstate',
            name='threshold',
        ),
        migrations.AddField(
            model_name='systemstate',
            name='city',
            field=models.CharField(default='Dakar', help_text='Ville pour la météo', max_length=100),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='latitude',
            field=models.FloatField(default=14.6928),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='longitude',
            field=models.FloatField(default=-17.4467),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='rain_expected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='threshold_max',
            field=models.FloatField(default=60, help_text="Seuil maximum d'humidité — la pompe s'arrête au dessus"),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='threshold_min',
            field=models.FloatField(default=30, help_text="Seuil minimum d'humidité — la pompe se déclenche en dessous"),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='mode',
            field=models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manuel')], default='auto', max_length=10),
        ),
    ]
